export const UserRowData = [
  {
    id: "#12345",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12322",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#123433",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12375",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12385",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#123665",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12387",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12355",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
  {
    id: "#12355",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    joinon: "April,20,2022",
  },
];
export const BlogsData = [
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    "Published On": "April 20,2022",
    view: "view",
    status: "Draft",
    statusColor: "navyBlue",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
  {
    id: "#12345",
    title: "Casino Trends 2023",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia mi tortor,",
    publish: "smith",
    view: "view",
    status: "published",
    statusColor: "primaryYellow",
  },
];
export const SubscriberRowData = [
  {
    id: "#12345",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12322",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#123433",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12375",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12385",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12349",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12349",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#123665",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12349",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12387",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12355",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
  {
    id: "#12355",
    name: "Adam",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
  },
];
export const SubmissionRowData = [
  {
    id: "#12345",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12322",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#123433",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12375",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12385",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#123665",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12349",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12387",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12355",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
  {
    id: "#12355",
    fname: "Adam",
    lname: "smith",
    email: "adam@gmail.com",
    phone: "123456789",
    date: "April,20,2022",
    subject: "Glistch",
    message: "View",
  },
];
